### ISSUE TITLE
Replace `expand=true` 

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1018]
We are using `expand=true`
On 3 places

1. https://github.com/aeternity/explorer-frontend/blob/7caf97828de582567aaff6a4000254ff4d2b0623/src/stores/names.js#L51
to display fees
https://master-explorer-frontend.prd.aepps.com/names?type=active

2. https://github.com/aeternity/explorer-frontend/blob/7caf97828de582567aaff6a4000254ff4d2b0623/src/stores/names.js#L65
to display fees
https://master-explorer-frontend.prd.aepps.com/names?type=expired

3. https://github.com/aeternity/explorer-frontend/blob/7caf97828de582567aaff6a4000254ff4d2b0623/src/stores/names.js#L70
to display fees
https://master-explorer-frontend.prd.aepps.com/
(section Names Recently activated)

**Comment by thepiwo** [comment]
Can you elaborate to replace with what?

**Comment by janmichek** [comment]
I don't have a strong preference.
The info I got, is that this will be deprecated and I should write down places in Explorer where we are using it.

**Comment by janmichek** [comment]
To get those fees values from a response even without `expand=true` ?

**Comment by thepiwo** [comment]
@sborrazas @jyeshe is there significant overhead in adding those in terms of calculation effort?

**Comment by marc0olo** [comment]
is it only about the "buy price" then, right?

**Comment by sborrazas** [comment]
The `expand=true` is being used on these three places:
- On the names nested list of claims/updates/transfers and on the revoke txi. When true, it turns the txis into a transaction object. Having these nested resources on separate endpoints (except on the revoke which is just one) we can always include the tx info without the need for `expand=true`.
- Same thing as before, but with nested oracle list of extends. It turns txis into txs.
- Same as before but with nested claims inside auctions. It turns txis into txs.

For the fees and last buyer on inactive names we can also always include the last claim, instead of the entire list of claims.

In addition, we could simply assume that `expand` is always `true` and make the necessary changes. I don't think we need to wait to get rid of unlimited nested lists to make this change.

**Comment by thepiwo** [comment]
but its a breaking change to change default behaviour, so why is it a problem to currently use `expand=true`?

**Comment by sborrazas** [comment]
@thepiwo yes, it would indeed be a breaking change. The advice on not using `expand=true` is because on the next versions most of the data obtained there will be removed

**Comment by sborrazas** [comment]
`expand` param is no longer needed, it always acts as if it was `true`
