### ISSUE TITLE
The edge cases of DOS protection

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#106]
### The previously fetched pages are preserved by the aepp and it requests future pages from the middle

Currently, in the superhero wallet, we are preserving the user's balance to speed up the initial load. We may want to do the same with transactions, in that case, the wallet will fetch transaction not from the first page, but from the last fetched. As I understand the current implementation of middleware is not supporting that.

### The aepp showing the list of transactions accepting the page in the URL

The storing the page in URL may be needed for:
- to be able to share the position in the list with another user
- to simplify indexing by search engine

In both cases, that URL may be opened directly and the current architecture will make us fetch all previous pages to show the desired one that is very ineffective.

### The aepp polls the first page and fetches the last page on demand (infinite scrolling)

It is unclear is it the case of DOS protection or not (the pages won't be requested subsequently, more like "1, 2, 3, 1, 1, 4, 5"). But definitely, it is reasonable to support that on the middleware level.

I think the best way to resolve these issues is to implement the support of fetching the random page.

**Comment by skkw** [comment]
Yes, skipping pages is not supported, so if you want page 2, you also need to ask for page 1 before.
(Also, since queries for all accounts can't be precomputed, every DB system would have to scan over that first page and throw it away... asking for request with high page number is vector for DOS as malicious clients could just send request with page=1000000 to halt the MDW.)

Since the `top` of the chain is moving constantly, what actually is on page 1, 2, ... depends on time.

However, to support the scenario where you would like to avoid paginating for account from start, you can use scope - like: `txs/fromTXI-toTXI` or `gen/fromGEN-toGEN`...

This way (using scope) we would have absolute reference to the point of history instead of temporary, relative one (page from the start).
