### ISSUE TITLE
Websocket serves different data than the REST endpoints

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1291]
Hey folks,

# Background: 
I'm implementing a live keyblocks, microblocks and transactions browser app that presents recently minted objects in the blockchain. On initialization of my browser I am fetching the state from REST API and then apply further updates through websocket subscription. Unfortunately, these sources of data don't serve identical content which leads to misrepresenting the real state of the blockchain

# Issues:

## Sending websocket message before an object is indexed in the db (?): 
From my observation, it looks like the WebSocket messages are sent immediately after receiving information about it from a Node. Indexing that data in the database seems to take between tens of ms to a few seconds. 

### Issue 1 - wrong transaction count
As a result, often a websocket client receives information about transactions, while REST API `/keyblocks` endpoint still does not account for their existence.

![image](https://user-images.githubusercontent.com/46789227/235867608-04544621-e760-4e29-ac61-6867248083e0.png)
![image](https://user-images.githubusercontent.com/46789227/235866899-7423e34f-7341-4482-96dd-78973925e867.png)

I didn't spot a similar problem with the microblocks count

### Issue 2 - missing properties
Keyblock and Microblock messages received through the websocket do not contain microblock_count and transaction_count properties. As far as I know, we are aiming towards unifying the responses from REST API and the websocket, so this is a major discrepancy that requires websocket messages to be augmented on the client side. 

### Issue 3 - receiving transactions and microblocks which are later moved to another keyblock
Just before minting a new keyblock websocket usually sends up to a few microblocks and transactions assigned to the old keyblock, which are later orphaned and moved to the freshly minted keyblock. It would be nice to either prevent such a situation completely or at least send a message informing that given transactions and keyblocks were reassigned to another keyblock.

## Adding indexing information to REST endpoints
Since a request to REST API might take a different time than a websocket message to start subscribing events related to a given object, there always will be a chance for unsynchronized communication. Therefore: 

### Issue 4 - there is no way to sync data between REST endpoint and websocket messages with 100% accuracy
I think this issue might be resolved by adding information to /keyblocks and /microblocks endpoints about which microblock and transaction has been indexed recently so we can compare it with the first message received from the websocket. If there is a mismatch, we can perform another request to REST API to sync everything.

---

As I mentioned multiple problems with the current APIs, I guess we should treat this issue as a general discussion about these problems and then create more granular issues to implement the results of that discussion.

**Comment by jyeshe** [comment]
@lukeromanowicz, commenting issue by issue:

_Issue 1 - wrong transaction count_
AFAIK it doesn't make sense a microblock without transaction returned by the REST API and needs to be investigated. What we can be sure about of is that the websockets transaction belongs to the indicated microblock since the broadcasting is per microblock, from which structure the transactions is extracted from.

_Issue 2 - missing properties_
A derived data that can be easily computed won't cause a major discrepancy. It can be included in the Mdw without worries.

_Issue 3 - receiving transactions and microblocks which are later moved to another keyblock_
Be it moved to the same generation or to one ahead, the affected generations are broadcasted again and the client should update the state accordingly from my understanding. 

_Issue 4 - there is no way to sync data between REST endpoint and websocket messages with 100% accuracy_
There is accuracy but there is also a delay intrinsic to the operation. The websocket sends the information and it's written to the REST API state right afterwards. Depending on the amount of data, latency and state of processing resources the REST API will show the very same microblocks with some delay.

What you think about using the microblocks count and its hashes to detect replaced generations? To know how recent the blocks are there would be a time field and for a relative comparison the micro blocks have also the index.

**Comment by jyeshe** [comment]
@lukeromanowicz I will add the extra `microblock_count` and `transaction_count` fields.
