### ISSUE TITLE
State channel transactions count is missing some of the transactions

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1302]
Looks like transactions count endpoint for state channels is missing some of the transactions. For example:

https://mainnet.aeternity.io/mdw/v2/txs/count/ch_2t1GrT3yDVwbiYMU5tMmgbeSW8ZPEuZPdGCDhQikePvLvWXFQE

returns:
```
{"channel_force_progress_tx":{"channel_id":1}}
```

While this state channel has at least two associated transactions:
https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&channel=ch_2t1GrT3yDVwbiYMU5tMmgbeSW8ZPEuZPdGCDhQikePvLvWXFQE

**Comment by sborrazas** [comment]
> @sborrazas is it really the same case? I'm getting two transactions from `/v2/txs` endpoint which would suggest that both of them are real transactions, not contract triggers

You're right, I was mistaken. The channel create transaction is never included in the counts, same happens with contracts creation (e.g. https://mainnet.aeternity.io/mdw/v2/txs/count/ct_2KyjN8awukUsvzqxPDtLjh6scYjDZEha3gU9LXET3VoTxc45Hv). I'll work on this, thank you for reporting

**Comment by sborrazas** [comment]
@lukeromanowicz I realized that this `/txs/count/:id` endpoint returns all transactions in which the `id` included on ANY of the transaction fields. In the case of a `ChannelCreateTx`, there's no field that contains the ID provided in the URL (https://mainnet.aeternity.io/v3/transactions/th_ucGC9qKK87smWYyvHgcepXxzKKRKubpAUGBBGR3M7XyyY8wdb), which is why it doesn't appear under the `/mdw/v2/txs/count/:id` endpoint

**Comment by lukeromanowicz** [comment]
@sborrazas I understand though I find this a little bit counterintuitive/inconsistent that it has a different logic than the parent endpoint (`/txs?channel=:id`). in such a case is there any way I can get the correct number of all *transactions* related to a given channel, including those that do not specify the exact id in any of the fields?

**Comment by sborrazas** [comment]
For any given channel, you can get the amount of updates on the channel detail endpoint: https://mainnet.aeternity.io/mdw/v2/channels/ch_2t1GrT3yDVwbiYMU5tMmgbeSW8ZPEuZPdGCDhQikePvLvWXFQE. You can even get them on the channels listing endpoint: https://mainnet.aeternity.io/mdw/v2/channels/

**Comment by lukeromanowicz** [comment]
@sborrazas I'm sorry, I didn't specify my needs correctly. What I mean is I need a data source that shows the correct count of all transactions in scope of a given state channel with distinction by transaction type (so I can implement filtering by type)

**Comment by sborrazas** [comment]
@lukeromanowicz the missing transaction is the ChannelCreate transaction, which is not considered an update. And it's not included in the `/txs/count?id=ch_...` endpoint because of the reasons I gave before: channel_id is not part of any of the fields of a ChannelCreateTx, while it is part of the other types of transactions (withdraw, slash, etc)

**Comment by sborrazas** [comment]
@lukeromanowicz can you confirm this is working as described before? if so, please close this issue

**Comment by lukeromanowicz** [comment]
I confirm that using `/txs/count?id=ch_...` endpoint + 1 is always returning the same count of transactions as endpoint:

`/v2/txs?direction=backward&channel=ch_...` 

Thank you very much for your help @sborrazas
