### ISSUE TITLE
Oracle queries are sometimes unavailable

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1429]
For some queries in oracles, we got the response as expected

**Example 1**

Reponses
https://mainnet.aeternity.io/mdw/v2/oracles/ok_g5vQK6beY3vsTJHH7KBusesyzq9WMdEYorF8VyvZURXTjLnxT/responses?limit=10

Queries
https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=1&type=oracle_query&oracle=ok_g5vQK6beY3vsTJHH7KBusesyzq9WMdEYorF8VyvZURXTjLnxT

But for some of them queries are empty.
I assume once we have some responses, there have to be according query to it, right?

**Example 2**

Reponses
https://mainnet.aeternity.io/mdw/v2/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc/responses?limit=10

Queries
https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=1&type=oracle_query&oracle=ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc

The thing I want to achieve is the missing Last Queried value
https://github.com/aeternity/aescan/issues/329

**Comment by sborrazas** [comment]
@janmichek in the second example, responses are made via `OracleRespondTx` but queries are made via contract calls:

https://mainnet.aeternity.io/mdw/v2/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc/responses?limit=10

and 

https://mainnet.aeternity.io/mdw/v2/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc/queries?limit=10

you can see this because the `source_tx_type` is `ContractCallTx` and not `OracleQueryTx`

**Comment by janmichek** [comment]
Aha, that explains a lot.

But I am still unable to use https://mainnet.aeternity.io/mdw/v2/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc/queries?limit=1 to display `last queried` because in the response there is no time value, not even block height per query. Any ideas on how to achieve this?


![image](https://github.com/aeternity/ae_mdw/assets/15363559/abd356d0-3701-41f5-af9d-c1c076e7e85a)

**Comment by sborrazas** [comment]
@janmichek this is being handled here https://github.com/aeternity/ae_mdw/issues/1418 it's not yet deployed, but will soon be. Feel free to close this issue in favor of that one
