### ISSUE TITLE
Duplicated events in activities

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1498]
Some of the activities in `/accounts/:id/activities` endpoint seem to be duplicated. An example is SpendTxEvent duplicated in:
https://mainnet.aeternity.io/mdw/v2/accounts/ak_2epACQAj2w8EBX4AVodp3c4NE5N4HVMRLW7KvsA2ncbRV4QNbT/activities?cursor=688270-36049280-0&limit=2&rev=1 referring to the same SpendTx

**Comment by sborrazas** [comment]
@lukeromanowicz in this case, both the sender and the recipient of that transaction are the same: https://mainnet.aeternity.io/mdw/v2/txs/th_2Pirj6ENnCimXEdgs4EJzQumLYbXa5vUeCfyeNQbEVgugDJAHv, which is why it appears twice.

I don't think it should be the expected behavior, I'll work on removing these duplications.

**Comment by lukeromanowicz** [comment]
Oh, you are right :O didn't noticed that. Yes, ideally it would be best to see only one event

**Comment by janmichek** [comment]
@sborrazas Seems like this has been implemented. Can I close this issue?

**Comment by sborrazas** [comment]
> @sborrazas Seems like this has been implemented. Can I close this issue?

Yes please. Thank you
