### ISSUE TITLE
Top accounts wealth is not up to date

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1661]
https://github.com/aeternity/ae_mdw/assets/15363559/3f6fe298-fffb-406d-ac11-80cd7b65bcb8

**Comment by michele-franchi** [comment]
@sborrazas @jyeshe any update?

**Comment by yaboiishere** [comment]
Hello, I'm trying to reproduce this in the testnet and it the wealth endpoint seems to be upating instantly. Is there a way to  check if this issue still persists, if it does think it might be due to the way the middleware stores and updates the balance data asynchronously, but I can't say for certain.

**Comment by janmichek** [comment]
Thanks for checking. When I replicate the scenario from the screen capture above, it still seems to be an issue.

**Comment by michele-franchi** [comment]
@yaboiishere this is reproducible using the mainnet endpoint:
https://mainnet.aeternity.io/mdw/v2/wealth

If you check a few accounts you will notice that the balance is not up to date. Here's the current data:

/wealth endpoint:
<img width="680" alt="image" src="https://github.com/aeternity/ae_mdw/assets/11598532/0c3e0f53-9aa9-4fff-95f8-455a426ffbd7">

Node data:
https://mainnet.aeternity.io/v3/accounts/ak_5tRWRq7cYfWRtjvvXGKqUKoDCbput3fBcvKv4FPPbeHbvMNYK
<img width="850" alt="image" src="https://github.com/aeternity/ae_mdw/assets/11598532/fcb0834d-bbe5-403d-987d-21a803e37ffe">

https://mainnet.aeternity.io/v3/accounts/ak_zAbG2GGWrYJeU3PinouJSCT9ujgmHFJRQVrMiUZGqrJRFXmuF
<img width="504" alt="image" src="https://github.com/aeternity/ae_mdw/assets/11598532/c21c2099-e21c-4fc8-b358-b23abb744162">

Balance is 0 but in the /wealth endpoint it's not.

**Comment by michele-franchi** [comment]
ping @yaboiishere

**Comment by yaboiishere** [comment]
Hey, sorry forgot to update, It's seems like a bigger problem than what i though. I've looked into the logs of the mdw and the code and i can't seem to find what is causing this issue. I'm trying to sync the middleware locally, so i can debug this, but that turned out to be really slow. I plan on coming back to this issue when i have it synced
