### ISSUE TITLE
make unit/integration tests independent from synced chain

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#220]

**Comment by sborrazas** [comment]
So after some digging into the different transactions we have, I thought it would be useful to have some declarative way of specifying a sample blockchain. This would not only make tests independent from the synced chain, but it will also make them clearer.

There's already been some talking about something similar for a thing called "chain simulator" on [this GH issue](https://github.com/aeternity/aeternity/issues/3693). In the future, it can not only be an Elixir-only thing, but also turned into some DSL that the chain simulator interpreter can run.

For writing Elixir tests, using exclusively Elixir data structres, I thought of having something like this:

```elixir
initial_balances = %{alice: 20_000, charlie: 30_000}

with_blockchain initial_balances, [ # with_blockchain would be a macro
  {:b1, {:kb, :alice}},
  {:b2, {:mb, :b2, [
      {:t1, {:spend_tx, :alice, :bob, 10_000}},
      {:t2, {:oracle_register, :bob, <<>>, <<>>}}, # Query format, response format
    ]}},
  {:b3, {:mb, :b3, [
      {:t3, {:contract_register, :charlie, "./contract-source.aes"}}
    ]}}
  {:b4, {:kb, :charlie}}
] do
  # 3 locally accessible variables
  #  - blocks       => map with info about blocks previously declared
  #  - accounts     => map with info about accounts previously declared
  #  - transactions => map with info about transactions previously declared

  # SAMPLE TEST 1
  block3 = blocks[:b3]
  block3_hash = block3[:hash]
  block3_miner = block3[:miner]

  assert %{"hash" => ^block3_hash, "miner" => ^block3_miner} = get(conn, "/block/#{block3_hash}")
    |> json_response(200)

  # SAMPLE TEST 2
  oracle_hash = transactions[:t2][:hash]

  assert %{"data" => [%{"hash" => ^oracle_hash}]} = get(conn, "/oracles?direction=backwards&limit=1")
    |> json_response(200)

  # SAMPLE TEST 3
  bob = accounts[:bob]
  bob_pubkey = bob[:pkey]

  assert %{"data" => [%{"amount" => 10_000}]} = get(conn, "/accounts/#{bob_pubkey}")
    |> json_response(200)
end
```

Since there's no way right now to create new blocks without mining and consensus, I thought this initial implementation would simply add the blocks to mnesia directly, with random hashes that don't have any validation.

Once the devmode is available, instead of inserting into mnesia directly, we could instead:

  1. Do a synchronous insertion of all of these blocks to the local running node
  2. Have MDW sync right after
  3. Run the tests

Thoughts?

**Comment by jyeshe** [comment]
I think it's valid and would certainty help. As an intermediary step, to decrease the effort required to insert data **consistently**, the factory could be mocked with a copy of some mainnet or testnet database records. In a later improved version would create things from scratch.

The factory could start with few and simple/standard operations (function names), if possible, to make it attractive to use:
- create and read for all data in model
- activate and inactivate for oracle and names
- transfer and balance for accounts and aex9
- so forth, something like these

So one could declare like in the setup above: transfer_account (or transfer_aex9), oracle_create, account_read, ...

**Comment by jyeshe** [comment]
Thinking once more about the declarative use, It's nice to have for aggregated initial states. However for transitions in the setup, the imperative way is more friendly with a direct help of the compiler and more familiar for newcomers. So instead of declaring a transfer the setup could call: `AccountTest.transfer(alice, bob, value)`

**Comment by thepiwo** [comment]
its done, but most test suites still need migration
