### ISSUE TITLE
figure out issue regarding transaction pagination

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#327]
https://testnet.aeternity.io/mdw/txs/backward?account=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&limit=30&page=1
https://testnet.aeternity.io/mdw/txs/backward?account=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&limit=30&page=2
https://testnet.aeternity.io/mdw/txs/backward?account=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&limit=30&page=3
https://testnet.aeternity.io/mdw/txs/backward?account=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&limit=30&page=100
every link is returning the same transactions

**Comment by thepiwo** [comment]
@sborrazas can you let @CedrikNikita know what the issue is here

**Comment by sborrazas** [comment]
This is happening because the frontend wasn't using the "next" field from the paginated resources response, and built the URLs on it's own doing `page=previous_page+1`. It has now being cleared up, and until the frontend doesn't start using the "next" field from the paginated responses we won't update the version. 

As of the new version, it won't use page=X anymore, instead it will use a cursor-based pagination. Still, regardless of what the URL might be, the frontend should always use the "next" field from the responses, because the way the URLs are built might change again in the future.
