### ISSUE TITLE
investigate sync speed bottlenecks

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#346]

**Comment by sborrazas** [comment]
These are the findings I concluded when syncing 250,000 generation forward:

1. Contract call transactions on the when processing the WriteLinksMutation
   This includes the two calls to mnesia:
     a. [Call to fetch the block](https://github.com/aeternity/ae_mdw/blob/master/lib/ae_mdw/db/sync/contract.ex#L36)
     b. [Call to fetch the contract creation txi](https://github.com/aeternity/ae_mdw/blob/master/lib/ae_mdw/db/sync/contract.ex#L38)
2. Contract events processing on the ContractEventsMutation
   This happens when calling [get_txi](https://github.com/aeternity/ae_mdw/blob/master/lib/ae_mdw/db/mutations/contract_events_mutation.ex#L27) to fetch the contract creation txi

All of these mutations processing ends up taking between 40ms and 80ms. There's quite a lot of these transactions, if we tackle these items we can get a much better performance improvement.

**Comment by jyeshe** [comment]
Profiling the reading from generation 0 to 540,000:
- loading blocks: 7h40m
- loading blocks + events: 12h (already with the optimization of #376)

Dry-running the txs to get 2 events in parallel reaches an improvement of 50% but degrades the performance after 300,000.

Since dry-running still represent almost 40% of total read time, an opportunity of optimization is to drop the transactions after contract calls (don't affect the events).
PS: The ones before the contract calls cannot be dropped from dry run because they change the chain state trees that are an input for contract calls dry run.

**Comment by jyeshe** [comment]
Here is a comparison on writing between Mnesia (mnesia_rocksdb) vs RocksDb (direct use of NIF):
```
names = :mnesia.dirty_all_keys(Model.ActiveName)
m_names = names |> Enum.take(100_000) |> Enum.flat_map(fn key -> :mnesia.dirty_read(Model.ActiveName, key) end)
delete = fn -> names |> Enum.take(100_000) |> Enum.each(fn key -> :mnesia.dirty_delete(Model.ActiveName, key) end); end
write100k = fn -> :timer.tc(fn -> :mnesia.sync_transaction(fn -> m_names |> Enum.each(fn m_name -> :mnesia.write(Model.ActiveName, m_name, :write) end) end) end) end
Enum.map(1..10, fn _i -> delete.(); Process.sleep(15_000); res = write100k.(); Process.sleep(15_000); res end) 
```
Result:
[
  {5050587, {:atomic, :ok}},
  {4639954, {:atomic, :ok}},
  {3789296, {:atomic, :ok}},
  {4121616, {:atomic, :ok}},
  {3814365, {:atomic, :ok}}
]
```
delete_rdb = fn -> names |> Enum.take(100_000) |> Enum.each(fn key -> AeMdw.Db.RocksDb.delete(Model.ActiveName, key) end); end
write100k_rdb = fn -> :timer.tc(fn -> m_names |> Enum.each(fn m_name -> key = :sext.encode(elem(m_name, 1)); value = :sext.encode(m_name); AeMdw.Db.RocksDb.put(Model.ActiveName, key, value) end); AeMdw.Db.RocksDb.commit() end) end
Enum.map(1..10, fn _i -> res = delete_rdb.(); Process.sleep(15_000); write100k_rdb.(); Process.sleep(15_000); res end)                                               
```
Result:
[
  {3156564, :ok}, 
  {2624777, :ok}, 
  {2380993, :ok}, 
  {2825805, :ok}, 
  {2816860, :ok}
 ]

Mnesia p90: 4716749 microsecs
RocksDb NIF: p90: 2990317.222222222

RocksDb being 57,7% faster
 
Notes:
1. `mnesia_rocksdb` currently don't support RocksDb (actual) transactions due to this issue:
https://gitlab.com/barrel-db/erlang-rocksdb/-/issues/120
2. RocksDB NIF was was used optimistic transaction db once it raises exception on conflict.

**Comment by jyeshe** [comment]
Here is a comparison on writing between Mnesia (mnesia_rocksdb) vs RocksDb (direct use of NIF):

names = :mnesia.dirty_all_keys(Model.ActiveName)
m_names = names |> Enum.take(100_000) |> Enum.flat_map(fn key -> :mnesia.dirty_read(Model.ActiveName, key) end)
delete = fn -> names |> Enum.take(100_000) |> Enum.each(fn key -> :mnesia.dirty_delete(Model.ActiveName, key) end); end
write100k = fn -> :timer.tc(fn -> :mnesia.sync_transaction(fn -> m_names |> Enum.each(fn m_name -> :mnesia.write(Model.ActiveName, m_name, :write) end) end) end) end
Enum.map(1..10, fn _i -> delete.(); Process.sleep(15_000); res = write100k.(); Process.sleep(15_000); res end) 

Result:
[
  {5526508, {:atomic, :ok}},
  {4736460, {:atomic, :ok}},
  {4686549, {:atomic, :ok}},
  {4107076, {:atomic, :ok}},
  {4291547, {:atomic, :ok}},
  {5171989, {:atomic, :ok}},
  {3902581, {:atomic, :ok}},
  {5071808, {:atomic, :ok}},
  {5706003, {:atomic, :ok}},
  {4956229, {:atomic, :ok}}
]

delete_rdb = fn -> names |> Enum.take(100_000) |> Enum.each(fn key -> AeMdw.Db.RocksDb.delete(Model.ActiveName, key) end); end
write100k_rdb = fn -> :timer.tc(fn -> m_names |> Enum.each(fn m_name -> key = :sext.encode(elem(m_name, 1)); value = :sext.encode(m_name); AeMdw.Db.RocksDb.put(Model.ActiveName, key, value) end); AeMdw.Db.RocksDb.commit() end) end
Enum.map(1..10, fn _i -> res = delete_rdb.(); Process.sleep(15_000); write100k_rdb.(); Process.sleep(15_000); res end)                                               

Result:
[
  {2937787, :ok},
  {3231083, :ok},
  {3160840, :ok},
  {3242770, :ok},
  {3017010, :ok},
  {2995460, :ok},
  {2890141, :ok},
  {3075234, :ok},
  {2745091, :ok},
  {2860209, :ok}
]
Mnesia p90: 4716749 microsecs
RocksDb NIF: p90: 2990317.222222222

RocksDb being 57,7% faster

Notes:

    mnesia_rocksdb currently don't support RocksDb (actual) transactions due to this issue:
    https://gitlab.com/barrel-db/erlang-rocksdb/-/issues/120
    RocksDB NIF was was used optimistic transaction db once it raises exception on conflict.

**Comment by thepiwo** [comment]
@sborrazas @jyeshe I feel our speed is still the same, but for very different reasons, should we re-investigate?

**Comment by sborrazas** [comment]
@thepiwo we should start tracking syncing time and syncing time per gen to be able to start comparing the time it takes. Perhaps we can work on #797 instead and close this one?

**Comment by thepiwo** [comment]
agree
