### ISSUE TITLE
name expiration consistency

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#396]
```
iex(aeternity@localhost)3> :mnesia.dirty_all_keys(Model.ActiveNameExpiration) |> Enum.group_by(fn {_height, name} -> name end) |> Enum.filter(fn {_name, expirations} -> length(expirations) > 1 end)
[
  {"payment.chain", [{538528, "payment.chain"}, {578734, "payment.chain"}]},
  {"9988776655.chain",
   [{632725, "9988776655.chain"}, {635550, "9988776655.chain"}]},
  {"xu.chain", [{645129, "xu.chain"}, {645130, "xu.chain"}]}
]
```
However, old expirations are always deleted on:
- update: https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/sync/name.ex#L127
- revoke: https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/sync/name.ex#L176
- expire: https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/name.ex#L74 

and created single time on:
- claim (double claim not allowed): https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/sync/name.ex#L63
- auction end: https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/name.ex#L109

PS: transfer changes only the owner and a name cannot be revoked during an auction (SDK doesn't continue with the operation).

**Comment by jyeshe** [comment]
@thepiwo @sborrazas here is there analysis that shows why we shouldn't have any name expiration issues. Summarizing, whenever a new expiration is saved and old is deleted (happen together in the same function without condition). The height of the old expiration deleted is also the very same height that was saved before (without any computation, read directly from the record).

The only possibility would be if the chain allowed in the past multiple claims (that would create duplicate expiration) or a revoke before auction end. Both are very less likely but I will add logs to confirm it.

**Comment by jyeshe** [comment]
Despite being sufficient the factor above, another factor that makes it even more clear the inconsistency on mnesia transactions is that these are intermittent issues for a sync execution that happens without concurrency in a single process with immutable input.

**Comment by thepiwo** [comment]
sounds good to me, so this issue can be closed?

**Comment by jyeshe** [comment]
Yes @thepiwo , smaller commits will fix it. If not by microblocks, with commits by transactions later.

**Comment by sborrazas** [comment]
I'm not particularly sure if those lines of code listed here do prove that the code itself doesn't let the database enter into an inconsistent state. For the following two reasons:

* It's using an ETS cache in between, which could potentially introduce bugs (caches always do)
* The keys used to write and delete the active auctions could potentially change between calls, we might be writing two `ActiveNameExpiration` with the same plain name and two different expirations because of some bug somewhere else through the code

I'm not saying mnesia might not be the root cause of the problem, but if it is then we are dealing with a **very serious consistency problem**. If mnesia doesn't provide any data guarantees (something that I haven't seen anywhere else before) then we ought to change databases and use something that does. We cannot provide users data that's inconsistent, even if we reduce the odds of it being inconsistent by making the transactions smaller (which we might do anyway for performance reasons, not consistency)

For these reasons, I suggest we dig deeper into these issues, perhaps by:
* Removing the ETS cache, and seeing if these errors continue to come up
* Logging every auction/name update and checking to see if those logs are consistent like I suggested before

I wouldn't rely of proving the absence of bugs by looking at the code, I don't think this has ever worked before

**Comment by jyeshe** [comment]
> I'm not particularly sure if those lines of code listed here do prove that the code itself doesn't let the database enter into an inconsistent state. For the following two reasons:
> 
>     * It's using an ETS cache in between, which could potentially introduce bugs (caches always do)
> 
>     * The keys used to write and delete the active auctions could potentially change between calls, we might be writing two `ActiveNameExpiration` with the same plain name and two different expirations because of some bug somewhere else through the code
> 
> 
> I'm not saying mnesia might not be the root cause of the problem, but if it is then we are dealing with a **very serious consistency problem**. If mnesia doesn't provide any data guarantees (something that I haven't seen anywhere else before) then we ought to change databases and use something that does. We cannot provide users data that's inconsistent, even if we reduce the odds of it being inconsistent by making the transactions smaller (which we might do anyway for performance reasons, not consistency)
> 
> For these reasons, I suggest we dig deeper into these issues, perhaps by:
> 
>     * Removing the ETS cache, and seeing if these errors continue to come up
> 
>     * Logging every auction/name update and checking to see if those logs are consistent like I suggested before
> 
> 
> I wouldn't rely of proving the absence of bugs by looking at the code, I don't think this has ever worked before

@sborrazas thank you for the considerations.

Regarding the ETS the operations are write/read through and happens always in the same sequence. With smaller commits there was no undeleted old expiration also. With a single process it should be deterministic, right?

Please have a look that there is no write for two different explorations (two simultaneous auctions are not allowed for the same name). We can add logs to check that the node has applied the rule throughout all generations though (the same for revoke rule and any other transition).

**Comment by jyeshe** [comment]
The expiration of the name was 84923 but it was revoked at `{{34923, 2}, 602473}` so its InactiveNameExpiration is `{34923, "pppkkk.test"}`.

It's not a bug but the name of the table can be improved (or documented) once it's used to save the height of deactivation.

**Comment by jyeshe** [comment]
At least since April 30 the `InactiveNameExpiration` also has the revoke height:
https://github.com/aeternity/ae_mdw/blob/07361e8469fa836650cf3071ff051ba60892fb9b/lib/ae_mdw/db/sync/name.ex#L157
