### ISSUE TITLE
decoding of bs_ does not remove the checksum

### ISSUE THREAD

**Issue by kryztoval** [aeternity/ae_mdw#40]
The bs_ decode function is not removing the 4 bytes at the end of the string that are used as a checksum, those should not be displayed

For example in this transaction: 
https://explorer.aeternity.io/transactions/th_2sRCaRst2jDZ2v9ChcSFsFavJQQNaDfkyoTeUksG9EMjGNQe4B

there are 4 garbage characters at the end, those are the checksum, those are removed properly by Aeknow and my middleware.

aeknow: https://www.aeknow.org/block/transaction/th_2sRCaRst2jDZ2v9ChcSFsFavJQQNaDfkyoTeUksG9EMjGNQe4B

my middleware: https://ae.criesca.net:3011/explorer/tx.html?hash=th_2sRCaRst2jDZ2v9ChcSFsFavJQQNaDfkyoTeUksG9EMjGNQe4B

**Comment by marc0olo** [comment]
@skkw is this still the case? I think @kryztoval is referring to the old middleware because this middleware isn't live yet, right?

**Comment by kryztoval** [comment]
I am referring to the one that is live right now in the address I posted

I thought this was the place that hosted the currently posted version

**Comment by skkw** [comment]
This is legacy middleware issue.

Lets keep this open for now so we can verify it's not happening in new MDW as well...

**Comment by skkw** [comment]
Not happening in new MDW, closing.

**Comment by kryztoval** [comment]
https://explorer.aeternity.io/transactions/th_vpWEs5upSQ6QZYTJBBL9dPB6xDPTozcNsgLv7YVNj6AjkF2uC

"This marks the moment .ani discovered the tipping bot. <3YâW"

It still fails to remove the checksum 'YâW'

**Comment by marc0olo** [comment]
according to the discussion in telegram this issue is related to the frontend of the middleware. though a frontend folder still exists in this repository it isn't used and thus it's correct to close the issue here.

@kryztoval you can open the issue in this repository https://github.com/aeternity/mdw-frontend/issues. not sure when it will be picked up and solved. but it shouldn't be a big deal. so we will see. maybe somebody of the community is able to solve it :-)

**Comment by kryztoval** [comment]
The issue is reported here.
https://github.com/aeternity/mdw-frontend/issues/54
